/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HighEndAppliancesIndexRouteImport } from './routes/high-end-appliances.index'
import { Route as HighEndAppliancesSlugRouteImport } from './routes/high-end-appliances.$slug'
import { Route as HvacIndexRouteImport } from './routes/hvac.index'
import { Route as HvacSlugRouteImport } from './routes/hvac.$slug'
import { Route as RefrigerationIndexRouteImport } from './routes/refrigeration.index'
import { Route as RefrigerationSlugRouteImport } from './routes/refrigeration.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HighEndAppliancesIndexRoute = HighEndAppliancesIndexRouteImport.update({
  id: '/high-end-appliances/',
  path: '/high-end-appliances/',
  getParentRoute: () => rootRouteImport,
} as any)
const HighEndAppliancesSlugRoute = HighEndAppliancesSlugRouteImport.update({
  id: '/high-end-appliances/$slug',
  path: '/high-end-appliances/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacIndexRoute = HvacIndexRouteImport.update({
  id: '/hvac/',
  path: '/hvac/',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacSlugRoute = HvacSlugRouteImport.update({
  id: '/hvac/$slug',
  path: '/hvac/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RefrigerationIndexRoute = RefrigerationIndexRouteImport.update({
  id: '/refrigeration/',
  path: '/refrigeration/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefrigerationSlugRoute = RefrigerationSlugRouteImport.update({
  id: '/refrigeration/$slug',
  path: '/refrigeration/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/high-end-appliances/$slug': typeof HighEndAppliancesSlugRoute
  '/hvac/$slug': typeof HvacSlugRoute
  '/refrigeration/$slug': typeof RefrigerationSlugRoute
  '/high-end-appliances/': typeof HighEndAppliancesIndexRoute
  '/hvac/': typeof HvacIndexRoute
  '/refrigeration/': typeof RefrigerationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/high-end-appliances/$slug': typeof HighEndAppliancesSlugRoute
  '/hvac/$slug': typeof HvacSlugRoute
  '/refrigeration/$slug': typeof RefrigerationSlugRoute
  '/high-end-appliances': typeof HighEndAppliancesIndexRoute
  '/hvac': typeof HvacIndexRoute
  '/refrigeration': typeof RefrigerationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/high-end-appliances/$slug': typeof HighEndAppliancesSlugRoute
  '/hvac/$slug': typeof HvacSlugRoute
  '/refrigeration/$slug': typeof RefrigerationSlugRoute
  '/high-end-appliances/': typeof HighEndAppliancesIndexRoute
  '/hvac/': typeof HvacIndexRoute
  '/refrigeration/': typeof RefrigerationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/high-end-appliances/$slug'
    | '/hvac/$slug'
    | '/refrigeration/$slug'
    | '/high-end-appliances/'
    | '/hvac/'
    | '/refrigeration/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/high-end-appliances/$slug'
    | '/hvac/$slug'
    | '/refrigeration/$slug'
    | '/high-end-appliances'
    | '/hvac'
    | '/refrigeration'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/high-end-appliances/$slug'
    | '/hvac/$slug'
    | '/refrigeration/$slug'
    | '/high-end-appliances/'
    | '/hvac/'
    | '/refrigeration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HighEndAppliancesSlugRoute: typeof HighEndAppliancesSlugRoute
  HvacSlugRoute: typeof HvacSlugRoute
  RefrigerationSlugRoute: typeof RefrigerationSlugRoute
  HighEndAppliancesIndexRoute: typeof HighEndAppliancesIndexRoute
  HvacIndexRoute: typeof HvacIndexRoute
  RefrigerationIndexRoute: typeof RefrigerationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/high-end-appliances/': {
      id: '/high-end-appliances/'
      path: '/high-end-appliances'
      fullPath: '/high-end-appliances/'
      preLoaderRoute: typeof HighEndAppliancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/high-end-appliances/$slug': {
      id: '/high-end-appliances/$slug'
      path: '/high-end-appliances/$slug'
      fullPath: '/high-end-appliances/$slug'
      preLoaderRoute: typeof HighEndAppliancesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac/': {
      id: '/hvac/'
      path: '/hvac'
      fullPath: '/hvac/'
      preLoaderRoute: typeof HvacIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac/$slug': {
      id: '/hvac/$slug'
      path: '/hvac/$slug'
      fullPath: '/hvac/$slug'
      preLoaderRoute: typeof HvacSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refrigeration/': {
      id: '/refrigeration/'
      path: '/refrigeration'
      fullPath: '/refrigeration/'
      preLoaderRoute: typeof RefrigerationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refrigeration/$slug': {
      id: '/refrigeration/$slug'
      path: '/refrigeration/$slug'
      fullPath: '/refrigeration/$slug'
      preLoaderRoute: typeof RefrigerationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HighEndAppliancesSlugRoute: HighEndAppliancesSlugRoute,
  HvacSlugRoute: HvacSlugRoute,
  RefrigerationSlugRoute: RefrigerationSlugRoute,
  HighEndAppliancesIndexRoute: HighEndAppliancesIndexRoute,
  HvacIndexRoute: HvacIndexRoute,
  RefrigerationIndexRoute: RefrigerationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
